#############################################################################
# Makefile for building: release/NMEA_Simulator
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  NMEA_Simulator.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile NMEA_Simulator.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease/.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = NMEA_Simulator1.0.0
DISTDIR = /home/intern/Downloads/nmea_simulator-main/release/.obj/NMEA_Simulator1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = release/.obj/

####### Files

SOURCES       = src/main.cpp \
		src/nmeadata.cpp \
		src/mainwindow.cpp \
		src/Dialogs/dptdialog.cpp \
		src/Dialogs/hdtdialog.cpp \
		src/Dialogs/mwvdialog.cpp \
		src/Dialogs/rotdialog.cpp \
		src/Dialogs/rsadialog.cpp \
		src/Dialogs/aamdialog.cpp \
		src/Dialogs/boddialog.cpp \
		src/Dialogs/serialportdialog.cpp \
		libs/RangeSlider/RangeSlider.cpp \
		src/threads.cpp \
		src/Dialogs/startupdialog.cpp release/.moc/moc_mainwindow.cpp \
		release/.moc/moc_dptdialog.cpp \
		release/.moc/moc_hdtdialog.cpp \
		release/.moc/moc_mwvdialog.cpp \
		release/.moc/moc_rotdialog.cpp \
		release/.moc/moc_rsadialog.cpp \
		release/.moc/moc_aamdialog.cpp \
		release/.moc/moc_boddialog.cpp \
		release/.moc/moc_serialportdialog.cpp \
		release/.moc/moc_RangeSlider.cpp \
		release/.moc/moc_threads.cpp \
		release/.moc/moc_startupdialog.cpp
OBJECTS       = release/.obj/main.o \
		release/.obj/nmeadata.o \
		release/.obj/mainwindow.o \
		release/.obj/dptdialog.o \
		release/.obj/hdtdialog.o \
		release/.obj/mwvdialog.o \
		release/.obj/rotdialog.o \
		release/.obj/rsadialog.o \
		release/.obj/aamdialog.o \
		release/.obj/boddialog.o \
		release/.obj/serialportdialog.o \
		release/.obj/RangeSlider.o \
		release/.obj/threads.o \
		release/.obj/startupdialog.o \
		release/.obj/moc_mainwindow.o \
		release/.obj/moc_dptdialog.o \
		release/.obj/moc_hdtdialog.o \
		release/.obj/moc_mwvdialog.o \
		release/.obj/moc_rotdialog.o \
		release/.obj/moc_rsadialog.o \
		release/.obj/moc_aamdialog.o \
		release/.obj/moc_boddialog.o \
		release/.obj/moc_serialportdialog.o \
		release/.obj/moc_RangeSlider.o \
		release/.obj/moc_threads.o \
		release/.obj/moc_startupdialog.o
DIST          = images/cancel_icon.png \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		NMEA_Simulator.pro include/datastructs.h \
		include/nmeadata.h \
		include/mainwindow.h \
		include/Dialogs/dptdialog.h \
		include/Dialogs/hdtdialog.h \
		include/Dialogs/mwvdialog.h \
		include/Dialogs/rotdialog.h \
		include/Dialogs/rsadialog.h \
		include/Dialogs/aamdialog.h \
		include/Dialogs/boddialog.h \
		include/Dialogs/serialportdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/threads.h \
		include/Dialogs/startupdialog.h src/main.cpp \
		src/nmeadata.cpp \
		src/mainwindow.cpp \
		src/Dialogs/dptdialog.cpp \
		src/Dialogs/hdtdialog.cpp \
		src/Dialogs/mwvdialog.cpp \
		src/Dialogs/rotdialog.cpp \
		src/Dialogs/rsadialog.cpp \
		src/Dialogs/aamdialog.cpp \
		src/Dialogs/boddialog.cpp \
		src/Dialogs/serialportdialog.cpp \
		libs/RangeSlider/RangeSlider.cpp \
		src/threads.cpp \
		src/Dialogs/startupdialog.cpp
QMAKE_TARGET  = NMEA_Simulator
DESTDIR       = release/
TARGET        = release/NMEA_Simulator


first: all
####### Build rules

release/NMEA_Simulator:  $(OBJECTS)  
	@test -d release/ || mkdir -p release/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NMEA_Simulator.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		NMEA_Simulator.pro
	$(QMAKE) -o Makefile NMEA_Simulator.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
NMEA_Simulator.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile NMEA_Simulator.pro

qmake_all: FORCE


all: Makefile release/NMEA_Simulator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/datastructs.h include/nmeadata.h include/mainwindow.h include/Dialogs/dptdialog.h include/Dialogs/hdtdialog.h include/Dialogs/mwvdialog.h include/Dialogs/rotdialog.h include/Dialogs/rsadialog.h include/Dialogs/aamdialog.h include/Dialogs/boddialog.h include/Dialogs/serialportdialog.h libs/RangeSlider/RangeSlider.h include/threads.h include/Dialogs/startupdialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/nmeadata.cpp src/mainwindow.cpp src/Dialogs/dptdialog.cpp src/Dialogs/hdtdialog.cpp src/Dialogs/mwvdialog.cpp src/Dialogs/rotdialog.cpp src/Dialogs/rsadialog.cpp src/Dialogs/aamdialog.cpp src/Dialogs/boddialog.cpp src/Dialogs/serialportdialog.cpp libs/RangeSlider/RangeSlider.cpp src/threads.cpp src/Dialogs/startupdialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: release/.moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) release/.moc/moc_predefs.h
release/.moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o release/.moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: release/.moc/moc_mainwindow.cpp release/.moc/moc_dptdialog.cpp release/.moc/moc_hdtdialog.cpp release/.moc/moc_mwvdialog.cpp release/.moc/moc_rotdialog.cpp release/.moc/moc_rsadialog.cpp release/.moc/moc_aamdialog.cpp release/.moc/moc_boddialog.cpp release/.moc/moc_serialportdialog.cpp release/.moc/moc_RangeSlider.cpp release/.moc/moc_threads.cpp release/.moc/moc_startupdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) release/.moc/moc_mainwindow.cpp release/.moc/moc_dptdialog.cpp release/.moc/moc_hdtdialog.cpp release/.moc/moc_mwvdialog.cpp release/.moc/moc_rotdialog.cpp release/.moc/moc_rsadialog.cpp release/.moc/moc_aamdialog.cpp release/.moc/moc_boddialog.cpp release/.moc/moc_serialportdialog.cpp release/.moc/moc_RangeSlider.cpp release/.moc/moc_threads.cpp release/.moc/moc_startupdialog.cpp
release/.moc/moc_mainwindow.cpp: include/mainwindow.h \
		include/datastructs.h \
		include/Dialogs/startupdialog.h \
		include/Dialogs/serialportdialog.h \
		include/nmeadata.h \
		include/Dialogs/aamdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/Dialogs/boddialog.h \
		include/Dialogs/dptdialog.h \
		include/Dialogs/rotdialog.h \
		include/Dialogs/mwvdialog.h \
		include/Dialogs/rsadialog.h \
		include/Dialogs/hdtdialog.h \
		include/threads.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/mainwindow.h -o release/.moc/moc_mainwindow.cpp

release/.moc/moc_dptdialog.cpp: include/Dialogs/dptdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/dptdialog.h -o release/.moc/moc_dptdialog.cpp

release/.moc/moc_hdtdialog.cpp: include/Dialogs/hdtdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/hdtdialog.h -o release/.moc/moc_hdtdialog.cpp

release/.moc/moc_mwvdialog.cpp: include/Dialogs/mwvdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/mwvdialog.h -o release/.moc/moc_mwvdialog.cpp

release/.moc/moc_rotdialog.cpp: include/Dialogs/rotdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/rotdialog.h -o release/.moc/moc_rotdialog.cpp

release/.moc/moc_rsadialog.cpp: include/Dialogs/rsadialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/rsadialog.h -o release/.moc/moc_rsadialog.cpp

release/.moc/moc_aamdialog.cpp: include/Dialogs/aamdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/aamdialog.h -o release/.moc/moc_aamdialog.cpp

release/.moc/moc_boddialog.cpp: include/Dialogs/boddialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/boddialog.h -o release/.moc/moc_boddialog.cpp

release/.moc/moc_serialportdialog.cpp: include/Dialogs/serialportdialog.h \
		include/datastructs.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/serialportdialog.h -o release/.moc/moc_serialportdialog.cpp

release/.moc/moc_RangeSlider.cpp: libs/RangeSlider/RangeSlider.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include libs/RangeSlider/RangeSlider.h -o release/.moc/moc_RangeSlider.cpp

release/.moc/moc_threads.cpp: include/threads.h \
		include/datastructs.h \
		include/nmeadata.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/threads.h -o release/.moc/moc_threads.cpp

release/.moc/moc_startupdialog.cpp: include/Dialogs/startupdialog.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/intern/Downloads/nmea_simulator-main/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/intern/Downloads/nmea_simulator-main -I/home/intern/Downloads/nmea_simulator-main/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/Dialogs/startupdialog.h -o release/.moc/moc_startupdialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

release/.obj/main.o: src/main.cpp include/mainwindow.h \
		include/datastructs.h \
		include/Dialogs/startupdialog.h \
		include/Dialogs/serialportdialog.h \
		include/nmeadata.h \
		include/Dialogs/aamdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/Dialogs/boddialog.h \
		include/Dialogs/dptdialog.h \
		include/Dialogs/rotdialog.h \
		include/Dialogs/mwvdialog.h \
		include/Dialogs/rsadialog.h \
		include/Dialogs/hdtdialog.h \
		include/threads.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/main.o src/main.cpp

release/.obj/nmeadata.o: src/nmeadata.cpp include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/nmeadata.o src/nmeadata.cpp

release/.obj/mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		include/datastructs.h \
		include/Dialogs/startupdialog.h \
		include/Dialogs/serialportdialog.h \
		include/nmeadata.h \
		include/Dialogs/aamdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/Dialogs/boddialog.h \
		include/Dialogs/dptdialog.h \
		include/Dialogs/rotdialog.h \
		include/Dialogs/mwvdialog.h \
		include/Dialogs/rsadialog.h \
		include/Dialogs/hdtdialog.h \
		include/threads.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/mainwindow.o src/mainwindow.cpp

release/.obj/dptdialog.o: src/Dialogs/dptdialog.cpp include/Dialogs/dptdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/dptdialog.o src/Dialogs/dptdialog.cpp

release/.obj/hdtdialog.o: src/Dialogs/hdtdialog.cpp include/Dialogs/hdtdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/hdtdialog.o src/Dialogs/hdtdialog.cpp

release/.obj/mwvdialog.o: src/Dialogs/mwvdialog.cpp include/Dialogs/mwvdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/mwvdialog.o src/Dialogs/mwvdialog.cpp

release/.obj/rotdialog.o: src/Dialogs/rotdialog.cpp include/Dialogs/rotdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/rotdialog.o src/Dialogs/rotdialog.cpp

release/.obj/rsadialog.o: src/Dialogs/rsadialog.cpp include/Dialogs/rsadialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/rsadialog.o src/Dialogs/rsadialog.cpp

release/.obj/aamdialog.o: src/Dialogs/aamdialog.cpp include/Dialogs/aamdialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/aamdialog.o src/Dialogs/aamdialog.cpp

release/.obj/boddialog.o: src/Dialogs/boddialog.cpp include/Dialogs/boddialog.h \
		libs/RangeSlider/RangeSlider.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/boddialog.o src/Dialogs/boddialog.cpp

release/.obj/serialportdialog.o: src/Dialogs/serialportdialog.cpp include/Dialogs/serialportdialog.h \
		include/datastructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/serialportdialog.o src/Dialogs/serialportdialog.cpp

release/.obj/RangeSlider.o: libs/RangeSlider/RangeSlider.cpp libs/RangeSlider/RangeSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/RangeSlider.o libs/RangeSlider/RangeSlider.cpp

release/.obj/threads.o: src/threads.cpp include/threads.h \
		include/datastructs.h \
		include/nmeadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/threads.o src/threads.cpp

release/.obj/startupdialog.o: src/Dialogs/startupdialog.cpp include/Dialogs/startupdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/startupdialog.o src/Dialogs/startupdialog.cpp

release/.obj/moc_mainwindow.o: release/.moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_mainwindow.o release/.moc/moc_mainwindow.cpp

release/.obj/moc_dptdialog.o: release/.moc/moc_dptdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_dptdialog.o release/.moc/moc_dptdialog.cpp

release/.obj/moc_hdtdialog.o: release/.moc/moc_hdtdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_hdtdialog.o release/.moc/moc_hdtdialog.cpp

release/.obj/moc_mwvdialog.o: release/.moc/moc_mwvdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_mwvdialog.o release/.moc/moc_mwvdialog.cpp

release/.obj/moc_rotdialog.o: release/.moc/moc_rotdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_rotdialog.o release/.moc/moc_rotdialog.cpp

release/.obj/moc_rsadialog.o: release/.moc/moc_rsadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_rsadialog.o release/.moc/moc_rsadialog.cpp

release/.obj/moc_aamdialog.o: release/.moc/moc_aamdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_aamdialog.o release/.moc/moc_aamdialog.cpp

release/.obj/moc_boddialog.o: release/.moc/moc_boddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_boddialog.o release/.moc/moc_boddialog.cpp

release/.obj/moc_serialportdialog.o: release/.moc/moc_serialportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_serialportdialog.o release/.moc/moc_serialportdialog.cpp

release/.obj/moc_RangeSlider.o: release/.moc/moc_RangeSlider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_RangeSlider.o release/.moc/moc_RangeSlider.cpp

release/.obj/moc_threads.o: release/.moc/moc_threads.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_threads.o release/.moc/moc_threads.cpp

release/.obj/moc_startupdialog.o: release/.moc/moc_startupdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_startupdialog.o release/.moc/moc_startupdialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/NMEA_Simulator/bin || mkdir -p $(INSTALL_ROOT)/opt/NMEA_Simulator/bin
	-$(QINSTALL_PROGRAM) release/$(QMAKE_TARGET) $(INSTALL_ROOT)/opt/NMEA_Simulator/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/NMEA_Simulator/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/NMEA_Simulator/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

